### ISSUE TITLE
Allow storing variable and use it to compare in assertions later

### ISSUE THREAD

**Issue by imballinst** [imballinst/text-to-playwright#1]
API example:

```yaml
tests:
  - name: Capture User ID
    steps:
      - Click "Generate User ID" button.
      - Store the value of "Generated User ID" element into variable `generated_user_id`.
      - Click "Users" link, then fill "User ID" input on the Real Users Section with value "{generated_user_id}".
      - Click "Submit" button on the Real Users Section.
      - Ensure "Real output" element on the Real Users Section to have value "{generated_user_id}".
```
